//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bedrijf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bedrijf()
        {
            this.CVItem = new HashSet<CVItem>();
        }
    
        public System.Guid BedrijfsId { get; set; }
        public string Bedrijfsnaam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVItem> CVItem { get; set; }
    }
}
