//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVItem
    {
        public System.Guid CVItemId { get; set; }
        public System.Guid PersoonID { get; set; }
        public string Functienaam { get; set; }
        public System.DateTime PeriodeVan { get; set; }
        public System.DateTime PeriodeTot { get; set; }
        public string Beschrijving { get; set; }
        public System.Guid BedrijfsID { get; set; }
    
        public virtual Bedrijf Bedrijf { get; set; }
        public virtual Persoon Persoon { get; set; }
    }
}
